### ISSUE TITLE
ShadowTH BigFoot Type B Breaks on Animation Import

### ISSUE THREAD

**Issue by dreamsyntax** [Psycrow101/Blender-3D-STH-Mtn-plugin#7]
```python
Python: Traceback (most recent call last):
  File "\Text", line 96, in <module>
  File "\Text", line 32, in convert_mtn_aio
  File "C:\Users\core\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\io_scene_sth_mtn\import_sth_mtn.py", line 135, in load
    act = create_mtn_action(root_obj, mtn)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\core\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\io_scene_sth_mtn\import_sth_mtn.py", line 116, in create_mtn_action
    for kf in mtn.bone_motions[b].keyframes:
              ~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

On loading the walk animation the model explodes
![image](https://github.com/user-attachments/assets/ba8836f4-1729-4260-89d5-19b14cb8eec4)

Ref
[BIGFOOTB.zip](https://github.com/user-attachments/files/17482086/BIGFOOTB.zip)

**Comment by Psycrow101** [comment]
Solved by https://github.com/Psycrow101/Blender-3D-STH-Mtn-plugin/commit/711779ac7ca17d37db998f90973efb6b65ae3039
